Unimarket.MVC/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using Unimarket.MVC.Models.CreateModels;
using Unimarket.MVC.Models.ViewModels;
using Unimarket.MVC.Services;

namespace Unimarket.MVC.Controllers
{
    public class CheckoutController : Controller
    {
		private readonly IHttpClientFactory _factory;
		private readonly ILogger<CartController> _logger;
		private readonly HttpClient _client;
		private readonly IHttpClientFactory _httpClientFactory;
		private readonly ICurrentUserService _currentUserService;
		public CheckoutController(ILogger<CartController> logger, IHttpClientFactory httpClientFactory,
			IConfiguration configuration, ICurrentUserService currentUserService)
		{
			_factory = httpClientFactory;
			_client = new HttpClient();
			_currentUserService = currentUserService;
			_client = _factory.CreateClient("ServerApi");
			_client.BaseAddress = new Uri(configuration["Cron:localhost"]);
		}
		[HttpGet]
		public async Task<IActionResult> Index()
        {
			var userId = HttpContext.Session.GetString("UserId");
			var response = await _client.GetAsync(_client.BaseAddress + $"Cart/get/usercart?userId={userId}");
			if (response.IsSuccessStatusCode) {
				ResponseCartVM cartItem = new ResponseCartVM();
				var data = await response.Content.ReadAsStringAsync();
				cartItem = JsonConvert.DeserializeObject<ResponseCartVM>(data);

				response = await _client.GetAsync(_client.BaseAddress + $"auth/profile/{userId}");
				data = await response.Content.ReadAsStringAsync();
				UserVM user = JsonConvert.DeserializeObject<UserVM>(data);

				CheckOutVM CheckOutVM = new CheckOutVM
				{
					Cart = cartItem,
					User = user,
				};
				return View(CheckOutVM);
			}
			return RedirectToAction("OrderHistory", "Profile");
		}
		[HttpPost]
        public async Task<IActionResult> CheckOut([FromBody] CheckOutCM model)
        {
            var userId = HttpContext.Session.GetString("UserId");
			CheckOutDTO checkOutDTO = new CheckOutDTO
			{
				UserId = userId,
				Address = model.Address,
				Note = model.Note,
				PaymentType = "Tiền mặt"
			};

            var response = await _client.PostAsync(_client.BaseAddress + $"Order/Checkout",
                 new StringContent(
                    JsonConvert.SerializeObject(checkOutDTO),
                    Encoding.UTF8,
                    "application/json"));
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Unimarket.MVC/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Unimarket.MVC.Helpers;
using Unimarket.MVC.Models.ViewModels;
using Unimarket.MVC.Services;

namespace Unimarket.MVC.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IHttpClientFactory _factory;
        private readonly ILogger<ProfileController> _logger;
        private readonly HttpClient _client;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ICurrentUserService _currentUserService;
        public ProfileController(ILogger<ProfileController> logger, IHttpClientFactory httpClientFactory,
            IConfiguration configuration, ICurrentUserService currentUserService)
        {
            _factory = httpClientFactory;
            _client = new HttpClient();
            _currentUserService = currentUserService;
            _client = _factory.CreateClient("ServerApi");
            _client.BaseAddress = new Uri(configuration["Cron:localhost"]);
        }

        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.Session.GetString("UserId");
            var response = await _client.GetAsync(_client.BaseAddress + $"auth/profile/{userId}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                UserVM user = JsonConvert.DeserializeObject<UserVM>(data);
                return View(user);
            }
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public async Task<IActionResult> OrderHistory([FromQuery] DefaultSearch defaultSearch)
        {
            var userId = HttpContext.Session.GetString("UserId");
            ResponseOrder orders = new ResponseOrder();
            var response = await _client.GetAsync(_client.BaseAddress + $"Order/user?userId={userId}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                orders = JsonConvert.DeserializeObject<ResponseOrder>(data);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
            return View(orders);
        }
        public async Task<IActionResult> OrderDetails([FromQuery] DefaultSearch defaultSearch, [FromQuery] string orderId)
        {
            var userId = HttpContext.Session.GetString("UserId");
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToAction("Login", "User");
            }


            ResponseOrder orders = new ResponseOrder();
            var response = await _client.GetAsync(_client.BaseAddress + $"Order/user?userId={userId}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                orders = JsonConvert.DeserializeObject<ResponseOrder>(data);

                var order = orders.Data.FirstOrDefault(o => o.Id == Guid.Parse(orderId));
                if (order == null)
                {
                    return NotFound();
                }

                return View(order); 
            }
            else
            {
                return RedirectToAction("OrderHistory");
            }
        }

    }
}

Unimarket.MVC/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
@functions {
    public bool IsActive(string controller, params string[] actions)
    {
        var routeData = ViewContext.RouteData;
        var currentController = routeData.Values["controller"]?.ToString();
        var currentAction = routeData.Values["action"]?.ToString();
        return string.Equals(currentController, controller, StringComparison.OrdinalIgnoreCase) &&
               actions.Any(action => string.Equals(currentAction, action, StringComparison.OrdinalIgnoreCase));
    }
}
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Accounts - Product Admin Template</title>
    <link rel="icon" type="image/x-icon" href="~/img/Logo avatar-01.png">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:400,700" />
    <script src="https://kit.fontawesome.com/49e9f98849.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/templatemo-style.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body id="reportsPage">
    <div class="" id="home">
        <nav class="navbar navbar-expand-xl">
            <div class="container h-100">
                <a class="navbar-brand" href="index.html">
                    <h1 class="tm-site-title mb-0">Product Admin</h1>
                </a>
                <button class="navbar-toggler ml-auto mr-0"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars tm-nav-icon"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto h-100">
                        <li class="nav-item">
                            <a class="nav-link @(IsActive("Dashboard", "Index") ? "active" : "")" href="@Url.Action("Index","Dashboard")">
                                <i class="fas fa-tachometer-alt"></i> Dashboard
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               href="#"
                               id="navbarDropdown"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false">
                                <i class="far fa-file-alt"></i>
                                <span> Reports <i class="fas fa-angle-down"></i> </span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Daily Report</a>
                                <a class="dropdown-item" href="#">Weekly Report</a>
                                <a class="dropdown-item" href="#">Yearly Report</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(IsActive("Product", "Index", "AddProduct") ? "active" : "")" href="@Url.Action("Index", "Product")">
                                <i class="fa-solid fa-cart-shopping"></i> Products
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link @(IsActive("Account", "Index") ? "active" : "")" href="@Url.Action("Index", "Account")">
                                <i class="far fa-user"></i> Accounts
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               href="#"
                               id="navbarDropdown"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false">
                                <i class="fas fa-cog"></i>
                                <span> Settings <i class="fas fa-angle-down"></i> </span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Profile</a>
                                <a class="dropdown-item" href="#">Billing</a>
                                <a class="dropdown-item" href="#">Customize</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item" style="display: flex;
    justify-content: center;
    align-items: center;">
                            <a class="nav-link d-block" href="#">
                                Admin,    <a href="@Url.Action("Logout", "User")"><b>Log out</b></a>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div>
            @RenderBody()
        </div>
        <footer class="tm-footer row tm-mt-small">
            <div class="col-12 font-weight-light">
                <p class="text-center text-white mb-0 px-4 small">
                    Copyright &copy; <b>2018</b> All rights reserved.

                    Design: <a rel="nofollow noopener" href="https://templatemo.com" class="tm-footer-link">Template Mo</a>
                </p>
            </div>
        </footer>
    </div>

    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/fontawesome.min.js"></script>
    <script src="~/js/moment.min.js"></script>
    <script src="~/js/Chart.min.js"></script>
    <script src="~/js/tooplate-scripts.js"></script>
    <script src="~/js/dashboard.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Unimarket.MVC/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor Accessor;
@{
    var user = @Accessor.HttpContext.Session.GetString("User_FullName");
    var cartSize = @Accessor.HttpContext.Session.GetInt32("Cart") != null ? @Accessor.HttpContext.Session.GetInt32("Cart") : 0;
}
@functions {
    public bool IsActive(string controller, params string[] actions)
    {
        var routeData = ViewContext.RouteData;
        var currentController = routeData.Values["controller"]?.ToString();
        var currentAction = routeData.Values["action"]?.ToString();
        return string.Equals(currentController, controller, StringComparison.OrdinalIgnoreCase) &&
               actions.Any(action => string.Equals(currentAction, action, StringComparison.OrdinalIgnoreCase));
    }
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Unimarket">
    <meta name="keywords" content="unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Unimarket</title>
    <link rel="icon" type="image/x-icon" href="~/img/Logo avatar-01.png">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/fontawesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="public/graindashboard/css/graindashboard.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Custom Styles -->
    <style>
        .fixed-header {
            position: fixed;
            width: 100%;
            top: 0;
            z-index: 1000;
            background-color: white;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .search-container {
            display: flex;
            align-items: center;
            border: 1px solid #000;
            border-radius: 25px;
            padding: 0px 10px;
            width: 300px;
            margin: 10px 0;
        }

        .search-input {
            border: none;
            outline: none;
            flex-grow: 1;
            padding: 5px 10px;
            border-radius: 25px;
        }

        .search-button {
            background: none;
            border: none;
            outline: none;
            cursor: pointer;
            padding: 5px;
        }

            .search-button i {
                font-size: 15px;
                color: #000;
            }

        body {
            padding-top: 80px; /* Adjust this value based on the height of your header */
        }
    </style>
</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header fixed-header">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-xl-2 col-lg-1">
                    <div class="header__logo">
                        <a href="@Url.Action("Index", "Home")"><img src="~/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-5">
                    <nav class="header__menu" style="margin-left:30px;">
                        <ul>
                            <li class="@(IsActive("Home", "Index") ? "active" : "")">
                                <a href="@Url.Action("Index", "Home")">Trang chủ</a>
                            </li>
                            <li class="@(IsActive("Shop", "Index") ? "active" : "")">
                                <a href="@Url.Action("Index", "Shop")">Sản phẩm</a>
                            </li>
                            <li class="@(IsActive("Blog", "Index") ? "active" : "")">
                                <a href="@Url.Action("Index", "Blog")">Tin Tức</a>
                            </li>
                            <li class="@(IsActive("Contact", "Index") ? "active" : "")">
                                <a href="@Url.Action("Index", "Contact")">Liên hệ</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class ="col-xl-2 col-lg-2">
                    <div class="search-container">
                        <form method="get" action="@Url.Action("Index", "Shop")">
                            <input type="text" name="keyword" class="search-input" placeholder="Tìm kiếm..." value="@ViewData["Keyword"]">
                            <button type="submit" class="search-button">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>

                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="header__right">
                        <div class="header__right__auth">
                            @if (user != null)
                            {
                                <a href="@Url.Action("Index", "Profile")">Chào, <b>@user</b> </a>
                                <a href="@Url.Action("Logout", "User")"><b>Log out</b></a>
                            }
                            else
                            {
                                <a href="@Url.Action("Login", "User")">Đăng nhập</a>
                                <a href="@Url.Action("Login", "User")">Đăng ký</a>
                            }
                        </div>
                        <ul class="header__right__widget">
@*                             <li><span class="icon_search search-switch"></span></li> *@
                            <li>
                                <a href="@Url.Action("Index", "Cart")">
                                    <span class="icon_bag_alt"></span>
@*                                     <div class="tip">2</div> *@
                                    <div class="tip">@cartSize</div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div>
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-7">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="./index.html"><img src="~/img/logo.png" style="width=60%;" alt=""></a>
                        </div>
                        <p>
                            Hãy đồng hành cùng Unimarket - nơi bạn có thể thỏa sức mua sắm một cách thuận lợi và tiết kiệm
                        </p>
                        <p>
                            Liên hệ với chúng tôi: <br />
                            <u>Unimarket8888@gmail.com</u> hoặc <u>039 514 0547</u>
                        </p>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-5">
                </div>
                <div class="col-lg-2 col-md-3 col-sm-4">
                </div>
                <div class="col-lg-4 col-md-8 col-sm-8">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 footer__widget">
                            <h6>Về Unimarket</h6>
                            <ul>
                                <li><a href="@Url.Action("Welcome","Contact")">Giới thiệu</a></li>
                                <li><a href="@Url.Action("Index","Contact")">Liên hệ</a></li>
                                <li><a href="#">Báo cáo</a></li>
                                <li><a href="#">Q&A</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-6 col-md-6 footer__widget">
                            <h6>Tài khoản</h6>
                            <ul>
                                <li>
                                    <a href="@((user == null) ? Url.Action("Login", "User") : Url.Action("Index", "Profile"))">
                                        Tài khoản của bạn
                                    </a>
                                </li>
                                <li>
                                    <a href="@((user == null) ? Url.Action("Login", "User") : Url.Action("OrderHistory", "Profile"))">
                                        Lịch sử đơn hàng
                                    </a>
                                </li>
                                <li>
                                    <a href="@((user == null) ? Url.Action("Login", "User") : Url.Action("Index", "Cart"))">
                                        Giỏ hàng
                                    </a>
                                </li>
                                <li>
                                    <a href="@((user == null) ? Url.Action("Login", "User") : Url.Action("Index", "Checkout"))">
                                        Checkout
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                    <p>Lô E2a-7, Đường D1, Đ. D1, Long Thạnh Mỹ, Thành Phố Thủ Đức.</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Search Begin -->
@*     <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Tram choa'.....">
            </form>
        </div>
    </div> *@
    <!-- Search End -->
    <!-- Js Plugins -->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/mixitup.min.js"></script>
    <script src="~/js/jquery.countdown.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.nicescroll.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.9.2/dist/umd/popper.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>